### ISSUE TITLE
[Feature] Consolidating GenAIExamples on Key Workloads

### ISSUE THREAD

**Issue by joshuayao** [opea-project/GenAIExamples#1216]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Running nodes

Single Node

#### Merging examples
Merge examples with similar/relative functionalities.
- [x] #1241 : ChatQnA = ChatQnA + FaqGen

The following merges will postpone to the next releases:
- [ ] #1239 : Finetuning = Instruction Tuning + RerankTuning
- [ ] #1240 : Translation  = Translation + CodeTrans
- [ ] #1242 : MultimodalQnA = VisualQnA + VideoQnA + MultimodalQnA
- [ ] : AgentQnA = AgentQnA + DocIndexRetriever (TBD)
- [ ] : WorkflowExecAgent move to GenAIComps (TBD)
- [ ] : ProductitySuite move to Enterprise RAG (TBD)
- [ ] Changes at CI
